// Re-export the small set of lucide icons we actually use. Centralizing keeps
// bundle size in check and lets us swap icon style later in one place.
export {
  Search,
  Plus,
  Inbox,
  User,
  Star,
  Clock,
  MessageSquare,
  Paperclip,
  Settings,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  Share2,
  Link2,
  MoreHorizontal,
  Filter,
  ArrowDownUp,
  Columns,
  Rows3,
  LayoutGrid,
  Bug,
  Upload,
  X,
  Trash2,
  Check,
  CornerDownLeft,
  AtSign,
  Code2,
  ListFilter,
  LogOut,
  Loader2,
  Flag,
  Tag,
  Users,
  Folder,
  Layers,
  GripVertical,
  PanelLeftClose,
  PanelLeftOpen,
  AlertOctagon,
} from 'lucide-react';
